# Generated by Django 6.0.2 on 2026-03-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('ROOM', 'Sala de reuniones'), ('EQUIPMENT', 'Equipo tecnológico'), ('TOOL', 'Herramienta manual')], max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('RESERVED', 'Reservado'), ('MAINTENANCE', 'En Mantenimiento'), ('DAMAGED', 'Dañado/Fuera de servicio')], default='AVAILABLE', max_length=20)),
            ],
        ),
    ]
