# Generated by Django 6.0.2 on 2026-03-19 21:05

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('position', models.CharField(max_length=120)),
                ('area', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('PHYSICAL', 'Fisico'), ('DIGITAL', 'Digital'), ('SPACE', 'Espacio')], max_length=20)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='resource',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='code',
            field=models.CharField(default=uuid.uuid4, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='responsible_area',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='technical_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('ASSIGNED', 'Asignado'), ('MAINTENANCE', 'En mantenimiento'), ('RETIRED', 'Dado de baja')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='resource.resourcetype'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('returned_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='resource.resource')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='resource.resourceassignee')),
            ],
            options={
                'ordering': ('-start_date', '-id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('resource',), name='unique_active_assignment_per_resource'), models.CheckConstraint(condition=models.Q(('returned_at__isnull', True), ('returned_at__gte', models.F('start_date')), _connector='OR'), name='assignment_returned_after_start')],
            },
        ),
    ]
