# Generated by Django 6.0.2 on 2026-03-15 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(blank=True, max_length=15, null=True)),
                ('identitydocument', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('dependence', models.CharField(choices=[('SYSTEMS', 'Sistemas'), ('ADMINISTRATION', 'Administración'), ('TEACHING', 'Docencia'), ('EXTERNAL', 'Personal Externo')], default='SYSTEMS', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('bibliography', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
